### ISSUE TITLE
Instana Pluging does not work

### ISSUE THREAD

**Issue by ConsultandJr** [instana/instana-grafana-datasource#96]
Sirs,

We are trying to be able to graph Instana metrics and we have not got a single graph.
We have tried several environments, Cloud, and local installation and the same error.
Every time we open the Instana DataSource, a huge error appears in a pop-up window that we cannot copy it and it disappears.
We move forward, we accept the connection and it tells us that it is successful.
When we want to build a graph, nothing appears in the filters: No types found with query
But we test by CURL command line and if they bring information.

LOG:
C%22,%5C%22showAdvancedSettings%5C%22:false,%5C%22hide%5C%22:false%7D%22%7D%5D" error="http: proxy error: context canceled"
t=2021-04-29T09:47:21-0400 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/9/instana/api/instana/version status=502 remote_addr=192.168.0.6 time_ms=9 size=0 referer="http://192.168.0.13:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Instana%22,%7B%22metricCategory%22:%7B%22label%22:%22Infrastructure%20built-in%20metrics%22,%22key%22:0%7D,%22timeShiftIsValid%22:true,%22customFilters%22:%5B%5D,%22aggregationFunction%22:%7B%22label%22:%22SUM%22%7D,%22metric%22:%7B%22key%22:null,%22label%22:%22-%22%7D,%22timeInterval%22:%7B%22key%22:%2260000%22,%22label%22:%221min%22%7D,%22showAdvancedSettings%22:false,%22hide%22:false,%22timeFilter%22:%7B%22from%22:1619700014000,%22to%22:1619703614000,%22windowSize%22:3600000%7D,%22stableHash%22:%22%7B%5C%22metricCategory%5C%22:0,%5C%22customFilters%5C%22:%5B%5D,%5C%22key%5C%22:%5C%22Q-e9dc8de5-d962-4634-ab4e-4f9f277c4de4-0%5C%22,%5C%22aggregationFunction%5C%22:%7B%5C%22label%5C%22:%5C%22SUM%5C%22%7D,%5C%22metric%5C%22:null,%5C%22timeInterval%5C%22:%5C%2260000%5C%22,%5C%22showAdvancedSettings%5C%22:false,%5C%22hide%5C%22:false%7D%22%7D%5D"
t=2021-04-29T09:47:43-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/undefined/api/instana/version status=404 remote_addr=192.168.0.6 time_ms=3 size=34491 referer=http://192.168.0.13:3000/datasources/edit/10/
t=2021-04-29T09:52:02-0400 lvl=eror msg="Datasource has already been updated by someone else. Please reload and try again" logger=context userId=1 orgId=1 uname=admin error="trying to update old version of datasource" remote_addr=192.168.0.6
t=2021-04-29T09:52:02-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/datasources/10 status=409 remote_addr=192.168.0.6 time_ms=1 size=94 referer=http://192.168.0.13:3000/datasources/edit/10/
t=2021-04-29T09:53:28-0400 lvl=eror msg="Datasource has already been updated by someone else. Please reload and try again" logger=context userId=1 orgId=1 uname=admin error="trying to update old version of datasource" remote_addr=192.168.0.6
t=2021-04-29T09:53:28-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/datasources/10 status=409 remote_addr=192.168.0.6 time_ms=5 size=94 referer=http://192.168.0.13:3000/datasources/edit/10/
t=2021-04-29T09:53:36-0400 lvl=eror msg="Datasource has already been updated by someone else. Please reload and try again" logger=context userId=1 orgId=1 uname=admin error="trying to update old version of datasource" remote_addr=192.168.0.6
t=2021-04-29T09:53:36-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/datasources/10 status=409 remote_addr=192.168.0.6 time_ms=4 size=94 referer=http://192.168.0.13:3000/datasources/edit/10/
t=2021-04-29T09:54:10-0400 lvl=eror msg="Datasource has already been updated by someone else. Please reload and try again" logger=context userId=1 orgId=1 uname=admin error="trying to update old version of datasource" remote_addr=192.168.0.6
t=2021-04-29T09:54:10-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/datasources/10 status=409 remote_addr=192.168.0.6 time_ms=1 size=94 referer=http://192.168.0.13:3000/datasources/edit/10/
t=2021-04-29T09:54:26-0400 lvl=info msg=Requesting logger=data-proxy-log url=https://serverapm.instana.io/api/monitoringState
t=2021-04-29T09:54:35-0400 lvl=info msg=Requesting logger=data-proxy-log url=https://serverapm.instana.io/api/instana/version

What a disappointment, what a way to waste time with these solutions.

**Comment by ConsultandJr** [comment]
An unexpected error happened
Detalles
TypeError: Cannot read property 'key' of undefined

    at t (http://192.168.0.13:3000/public/plugins/instana-datasource/module.js:2:58686)
    at div
    at t (http://192.168.0.13:3000/public/plugins/instana-datasource/module.js:2:98104)
    at div
    at div
    at t (http://192.168.0.13:3000/public/build/explore.1c3a1c85d09a392be724.js:1:54990)
    at O (http://192.168.0.13:3000/public/build/vendors~app.1c3a1c85d09a392be724.js:2:90047)
    at div
    at t (http://192.168.0.13:3000/public/build/explore.1c3a1c85d09a392be724.js:1:234278)
    at div
    at div
    at t (http://192.168.0.13:3000/public/build/explore.1c3a1c85d09a392be724.js:1:309570)
    at WithTheme(undefined)
    at O (http://192.168.0.13:3000/public/build/vendors~app.1c3a1c85d09a392be724.js:2:90047)
    at div
    at t (http://192.168.0.13:3000/public/build/explore.1c3a1c85d09a392be724.js:1:48148)
    at WithTheme(undefined)
    at O (http://192.168.0.13:3000/public/build/vendors~app.1c3a1c85d09a392be724.js:2:90047)
    at t (http://192.168.0.13:3000/public/build/app.1c3a1c85d09a392be724.js:2:1962792)
    at t (http://192.168.0.13:3000/public/build/app.1c3a1c85d09a392be724.js:2:1963322)
    at div
    at div
    at div
    at t (http://192.168.0.13:3000/public/build/vendors~app.1c3a1c85d09a392be724.js:2:1037092)
    at m (http://192.168.0.13:3000/public/build/app.1c3a1c85d09a392be724.js:2:3052492)
    at div
    at t (http://192.168.0.13:3000/public/build/explore.1c3a1c85d09a392be724.js:1:236763)
    at O (http://192.168.0.13:3000/public/build/vendors~app.1c3a1c85d09a392be724.js:2:90047)
    at n (http://192.168.0.13:3000/public/build/vendors~app.1c3a1c85d09a392be724.js:2:663493)
    at t (http://192.168.0.13:3000/public/build/app.1c3a1c85d09a392be724.js:2:1801003)
    at h (http://192.168.0.13:3000/public/build/app.1c3a1c85d09a392be724.js:2:2976183)
    at t (http://192.168.0.13:3000/public/build/app.1c3a1c85d09a392be724.js:2:1962792)
    at t (http://192.168.0.13:3000/public/build/app.1c3a1c85d09a392be724.js:2:1963322)
    at l (http://192.168.0.13:3000/public/build/vendors~app.1c3a1c85d09a392be724.js:2:87654)

**Comment by Dalje-et** [comment]
Hi @ConsultandJr,

thanks for using the plugin and I'm really sorry to hear that you are experiencing issues. I just have a quick question: In your error logs I see the URL `https://serverapm.instana.io`. This is not a valid Instana URL however. Are you sure you are configuring the datasource with the correct input? 

If you really are sure then I would recommend you create a ticket in our support system via https://support.instana.com/hc/en-us/requests/new for faster resolution.

Again, sorry for the inconvenience we have caused you. Looking forward to your feedback.
